name: Check Documentation Pull Request

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Build the documentation using Sphinx
      - uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -b html ./source/ _build"
          docs-folder: "docs/"

      # Upload the built documentation as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/_build